import Head from 'next/head';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import FunFact from '../components/FunFact';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import TeamSlider from '../components/Slider/TeamSlider';
import Spacing from '../components/Spacing';

export default function About() {
  // FunFact Data
  const funfaceData = [
    {
      title: 'Global artists',
      factNumber: '100',
    },
    {
      title: 'Events Completed',
      factNumber: '100',
    },
    {
      title: 'Community Members',
      factNumber: '245',
    }
  ];

  return (
    <>
      <Head>
        <title>Home - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>

        {/* Start About Section */}
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-7">
              <SectionHeading
                title="Your trusted partner for business"
                subtitle="About Our Us"
              >
                <Spacing lg="30" md="20" />
                <p className="cs-m0">
                  ACES is dedicated to bringing you the finest experiences through our social media platform,
                  enabling art, artists and art enthusiasts to thrive together. Artists can network with each
                  other under the platform and have endless possibilities for collaboration and joint gigs.
                  We are an art lover's paradise, where people from all walks of life who are passionate about 
                  art can grow and flourish; be it art lovers, musicians, dancers, technicians and many more, 
                  everyone can be a part of our community.
                  We work to ensure visibility, transparency and a dedicated platform for artists to showcase 
                  their art and grow exponentially, letting the audience interact and resonate with their art 
                  in the best ways possible. We work towards incorporating the best trends, technologies and 
                  ideas for our artists and art enthusiasts for expanding and diversifying.
                </p>
                <Spacing lg="30" md="30" />
                <Div className="cs-separator cs-accent_bg"></Div>
                <Spacing lg="25" md="40" />
              </SectionHeading>
            </Div>
            <Div className="col-lg-5 offset-xl-2">
              <img
                src="/images/about_img_1.jpeg"
                alt="About"
                className="w-100 cs-radius_15"
              />
              <Spacing lg="25" md="25" />
            </Div>
          </Div>
        </Div>
        <Spacing lg="75" md="55" />
        {/* End About Section */}

        {/* Start Fun Fact Section */}
        <Div className="container">
          <FunFact
            title="Our fun fact"
            subtitle="Be a part of  our community."
            data={funfaceData}
          />
        </Div>
        {/* End Fun Fact Section */}


        {/* Start Team Section */}
        <Spacing lg="145" md="80" />
        <Div className="container">
          <SectionHeading
            title="Awesome team <br/>"
            subtitle="Our Team"
            variant="cs-style1"
          />
          <Spacing lg="85" md="45" />
          <TeamSlider />
        </Div>
        {/* End Team Section */}

      </Layout>
    </>
  );
}
